"""initial schema

Revision ID: 7a5ba742b190
Revises: 
Create Date: 2026-04-20 15:23:16.899547
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7a5ba742b190'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE FUNCTION set_updated_at()
    RETURNS trigger AS $$
    BEGIN
        NEW.updated_at = now();
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql
    """)
    op.create_table('products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('compliance_status', sa.Enum('allowed', 'restricted', 'banned', name='compliance_status'), server_default=sa.text("'allowed'"), nullable=False),
    sa.Column('allowed_for_sale', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('hold_reason', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=50), server_default=sa.text("'FL'"), nullable=False),
    sa.Column('last_compliance_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("name <> ''", name='ck_products_name_non_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_allowed_for_sale', 'products', ['allowed_for_sale'], unique=False)
    op.create_index('ix_products_category', 'products', ['category'], unique=False)
    op.create_index('ix_products_compliance_status', 'products', ['compliance_status'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default=sa.text("'America/New_York'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code <> ''", name='ck_stores_code_non_empty'),
    sa.CheckConstraint("name <> ''", name='ck_stores_name_non_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_stores_is_active', 'stores', ['is_active'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('flavor', sa.String(length=100), nullable=True),
    sa.Column('size_label', sa.String(length=50), nullable=True),
    sa.Column('unit_count', sa.Integer(), nullable=True),
    sa.Column('puff_count', sa.Integer(), nullable=True),
    sa.Column('thc_strength', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sku <> ''", name='ck_product_variants_sku_non_empty'),
    sa.CheckConstraint('cost IS NULL OR cost >= 0', name='ck_product_variants_cost_non_negative'),
    sa.CheckConstraint('price >= 0', name='ck_product_variants_price_non_negative'),
    sa.CheckConstraint('puff_count IS NULL OR puff_count > 0', name='ck_product_variants_puff_count_positive'),
    sa.CheckConstraint('unit_count IS NULL OR unit_count > 0', name='ck_product_variants_unit_count_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('sku', name='uq_product_variants_sku')
    )
    op.create_index('ix_product_variants_is_active', 'product_variants', ['is_active'], unique=False)
    op.create_index('ix_product_variants_product_id', 'product_variants', ['product_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'manager', 'staff', 'driver', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_store_id', 'users', ['store_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reorder_threshold', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Enum('available', 'reserved', 'sold', 'flagged', 'quarantined', name='inventory_status'), server_default=sa.text("'available'"), nullable=False),
    sa.Column('last_counted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_on_hand >= 0', name='ck_inventory_items_quantity_on_hand_non_negative'),
    sa.CheckConstraint('quantity_reserved <= quantity_on_hand', name='ck_inventory_items_reserved_lte_on_hand'),
    sa.CheckConstraint('quantity_reserved >= 0', name='ck_inventory_items_quantity_reserved_non_negative'),
    sa.CheckConstraint('reorder_threshold >= 0', name='ck_inventory_items_reorder_threshold_non_negative'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'variant_id', name='uq_inventory_store_variant')
    )
    op.create_index('ix_inventory_items_status', 'inventory_items', ['status'], unique=False)
    op.create_index('ix_inventory_items_store_id', 'inventory_items', ['store_id'], unique=False)
    op.create_index('ix_inventory_items_variant_id', 'inventory_items', ['variant_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('customer_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'preparing', 'ready', 'out_for_delivery', 'delivered', 'canceled', 'returned', name='order_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('age_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('age_verified_by_user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('subtotal_amount >= 0', name='ck_orders_subtotal_amount_non_negative'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_orders_tax_amount_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_orders_total_amount_non_negative'),
    sa.CheckConstraint('total_amount >= subtotal_amount', name='ck_orders_total_amount_gte_subtotal'),
    sa.ForeignKeyConstraint(['age_verified_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_store_id', 'orders', ['store_id'], unique=False)
    op.create_table('inventory_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('performed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('movement_type', sa.Enum('receipt', 'adjustment', 'reservation', 'sale', 'cancellation', 'return', 'damage', 'compliance_hold', name='inventory_movement_type'), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True, comment='Polymorphic source type for the related business record, such as order or adjustment.'),
    sa.Column('reference_id', sa.UUID(), nullable=True, comment='Polymorphic UUID reference to the related business record identified by reference_type.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(reference_type IS NULL AND reference_id IS NULL) OR (reference_type IS NOT NULL AND reference_id IS NOT NULL)', name='ck_inventory_logs_reference_pair_consistent'),
    sa.CheckConstraint('quantity_after >= 0', name='ck_inventory_logs_quantity_after_non_negative'),
    sa.CheckConstraint('quantity_delta <> 0', name='ck_inventory_logs_quantity_delta_non_zero'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_logs_created_at', 'inventory_logs', ['created_at'], unique=False)
    op.create_index('ix_inventory_logs_inventory_item_id', 'inventory_logs', ['inventory_item_id'], unique=False)
    op.create_index('ix_inventory_logs_reference_type', 'inventory_logs', ['reference_type'], unique=False)
    op.create_index('ix_inventory_logs_store_id', 'inventory_logs', ['store_id'], unique=False)
    op.create_index('ix_inventory_logs_variant_id', 'inventory_logs', ['variant_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('line_total >= 0', name='ck_order_items_line_total_non_negative'),
    sa.CheckConstraint('line_total >= unit_price', name='ck_order_items_line_total_gte_unit_price'),
    sa.CheckConstraint('quantity > 0', name='ck_order_items_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_order_items_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'variant_id', name='uq_order_items_order_variant')
    )
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('ix_order_items_variant_id', 'order_items', ['variant_id'], unique=False)
    op.execute("""
    CREATE TRIGGER trg_products_set_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at()
    """)
    op.execute("""
    CREATE TRIGGER trg_stores_set_updated_at
    BEFORE UPDATE ON stores
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at()
    """)
    op.execute("""
    CREATE TRIGGER trg_product_variants_set_updated_at
    BEFORE UPDATE ON product_variants
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at()
    """)
    op.execute("""
    CREATE TRIGGER trg_users_set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at()
    """)
    op.execute("""
    CREATE TRIGGER trg_inventory_items_set_updated_at
    BEFORE UPDATE ON inventory_items
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at()
    """)
    op.execute("""
    CREATE TRIGGER trg_orders_set_updated_at
    BEFORE UPDATE ON orders
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at()
    """)
    op.execute("""
    CREATE TRIGGER trg_order_items_set_updated_at
    BEFORE UPDATE ON order_items
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at()
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_order_items_set_updated_at ON order_items")
    op.execute("DROP TRIGGER IF EXISTS trg_orders_set_updated_at ON orders")
    op.execute("DROP TRIGGER IF EXISTS trg_inventory_items_set_updated_at ON inventory_items")
    op.execute("DROP TRIGGER IF EXISTS trg_users_set_updated_at ON users")
    op.execute("DROP TRIGGER IF EXISTS trg_product_variants_set_updated_at ON product_variants")
    op.execute("DROP TRIGGER IF EXISTS trg_stores_set_updated_at ON stores")
    op.execute("DROP TRIGGER IF EXISTS trg_products_set_updated_at ON products")
    op.drop_index('ix_order_items_variant_id', table_name='order_items')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_inventory_logs_variant_id', table_name='inventory_logs')
    op.drop_index('ix_inventory_logs_store_id', table_name='inventory_logs')
    op.drop_index('ix_inventory_logs_reference_type', table_name='inventory_logs')
    op.drop_index('ix_inventory_logs_inventory_item_id', table_name='inventory_logs')
    op.drop_index('ix_inventory_logs_created_at', table_name='inventory_logs')
    op.drop_table('inventory_logs')
    op.drop_index('ix_orders_store_id', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_inventory_items_variant_id', table_name='inventory_items')
    op.drop_index('ix_inventory_items_store_id', table_name='inventory_items')
    op.drop_index('ix_inventory_items_status', table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index('ix_users_store_id', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_product_variants_product_id', table_name='product_variants')
    op.drop_index('ix_product_variants_is_active', table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index('ix_stores_is_active', table_name='stores')
    op.drop_table('stores')
    op.drop_index('ix_products_compliance_status', table_name='products')
    op.drop_index('ix_products_category', table_name='products')
    op.drop_index('ix_products_allowed_for_sale', table_name='products')
    op.drop_table('products')
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    op.execute("DROP TYPE IF EXISTS order_status")
    op.execute("DROP TYPE IF EXISTS inventory_movement_type")
    op.execute("DROP TYPE IF EXISTS inventory_status")
    op.execute("DROP TYPE IF EXISTS user_role")
    op.execute("DROP TYPE IF EXISTS compliance_status")
    # ### end Alembic commands ###
