// NubeRush Driver — core API transport client (Dr.1.3.C).
//
// A single, tiny request layer that every feature data source will go through.
// It mirrors the web client's transport semantics conceptually
// (web/src/api/client.ts) — NOT its UI, router, or state management:
//
//   - Path is joined onto the configured base URL (leading "/" optional).
//   - Authorization: Bearer <token> is attached when the (optional) token
//     provider yields a non-empty token; no provider / null token => no header.
//   - Accept: application/json is always sent.
//   - Content-Type: application/json is set when a JSON body is provided.
//   - Optional Idempotency-Key header for safe retries of compliance actions
//     (the keys themselves are generated by callers in later subphases).
//   - 2xx JSON  -> decoded body.
//   - 204 / empty body -> null.
//   - non-2xx   -> throws ApiError (normalized FastAPI/JSON/text/empty).
//   - transport failure -> throws ApiError.network (status 0).
//
// Deliberately NOT implemented here (later subphases / out of scope):
//   - automatic retries, caching, offline queueing
//   - Supabase auth (Dr.1.3.D supplies the token provider)
//   - any driver endpoint-specific wrapper or business logic
//   - any UI/state mutation

import 'dart:convert';

import 'package:http/http.dart' as http;

import 'api_config.dart';
import 'api_error.dart';

/// Supplies the current access token, or `null` when there is no session.
///
/// Dr.1.3.C defines only the type; Dr.1.3.D wires it to the Supabase session.
typedef AccessTokenProvider = Future<String?> Function();

/// Supported HTTP methods for the core client.
enum ApiMethod { get, post, patch, delete }

/// Thin transport over [http.Client] with centralized headers, JSON
/// encode/decode, and error normalization.
class ApiClient {
  ApiClient({
    required ApiConfig config,
    required http.Client httpClient,
    AccessTokenProvider? accessTokenProvider,
  })  : _config = config,
        _httpClient = httpClient,
        _accessTokenProvider = accessTokenProvider;

  final ApiConfig _config;
  final http.Client _httpClient;
  final AccessTokenProvider? _accessTokenProvider;

  Future<dynamic> get(
    String path, {
    Map<String, dynamic>? query,
    String? idempotencyKey,
    Map<String, String>? headers,
  }) =>
      request(
        ApiMethod.get,
        path,
        query: query,
        idempotencyKey: idempotencyKey,
        headers: headers,
      );

  Future<dynamic> post(
    String path, {
    Object? body,
    Map<String, dynamic>? query,
    String? idempotencyKey,
    Map<String, String>? headers,
  }) =>
      request(
        ApiMethod.post,
        path,
        body: body,
        query: query,
        idempotencyKey: idempotencyKey,
        headers: headers,
      );

  Future<dynamic> patch(
    String path, {
    Object? body,
    Map<String, dynamic>? query,
    String? idempotencyKey,
    Map<String, String>? headers,
  }) =>
      request(
        ApiMethod.patch,
        path,
        body: body,
        query: query,
        idempotencyKey: idempotencyKey,
        headers: headers,
      );

  Future<dynamic> delete(
    String path, {
    Object? body,
    Map<String, dynamic>? query,
    String? idempotencyKey,
    Map<String, String>? headers,
  }) =>
      request(
        ApiMethod.delete,
        path,
        body: body,
        query: query,
        idempotencyKey: idempotencyKey,
        headers: headers,
      );

  /// Perform a request and return the decoded JSON body, or `null` for an
  /// empty / 204 response.
  ///
  /// Throws [ApiError] for non-2xx responses and for transport failures.
  Future<dynamic> request(
    ApiMethod method,
    String path, {
    Object? body,
    Map<String, dynamic>? query,
    String? idempotencyKey,
    Map<String, String>? headers,
  }) async {
    final Uri url = _buildUri(path, query);
    final Map<String, String> finalHeaders =
        await _buildHeaders(body: body, idempotencyKey: idempotencyKey, extra: headers);
    final String? encodedBody = body == null ? null : jsonEncode(body);

    http.Response response;
    try {
      response = await _send(method, url, finalHeaders, encodedBody);
    } catch (err) {
      // Any transport-level failure (socket, DNS, TLS, etc.) -> status 0.
      throw ApiError.network();
    }

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw ApiError.fromResponse(
        status: response.statusCode,
        body: response.body,
      );
    }

    return _decodeSuccess(response);
  }

  Future<http.Response> _send(
    ApiMethod method,
    Uri url,
    Map<String, String> headers,
    String? body,
  ) {
    switch (method) {
      case ApiMethod.get:
        return _httpClient.get(url, headers: headers);
      case ApiMethod.post:
        return _httpClient.post(url, headers: headers, body: body);
      case ApiMethod.patch:
        return _httpClient.patch(url, headers: headers, body: body);
      case ApiMethod.delete:
        return _httpClient.delete(url, headers: headers, body: body);
    }
  }

  /// Join [path] onto the base URI without producing double slashes, and merge
  /// query parameters (values stringified; null values dropped).
  Uri _buildUri(String path, Map<String, dynamic>? query) {
    final String basePath = _config.baseUri.path; // already trailing-slash free
    final String suffix = path.startsWith('/') ? path : '/$path';
    final String joinedPath = '$basePath$suffix';

    Map<String, String>? queryParams;
    if (query != null && query.isNotEmpty) {
      queryParams = <String, String>{};
      query.forEach((String key, dynamic value) {
        if (value != null) queryParams![key] = '$value';
      });
      if (queryParams.isEmpty) queryParams = null;
    }

    return _config.baseUri.replace(
      path: joinedPath,
      queryParameters: queryParams,
    );
  }

  Future<Map<String, String>> _buildHeaders({
    required Object? body,
    required String? idempotencyKey,
    required Map<String, String>? extra,
  }) async {
    final Map<String, String> headers = <String, String>{
      'Accept': 'application/json',
    };

    if (body != null) {
      headers['Content-Type'] = 'application/json';
    }

    final String? token = await _accessTokenProvider?.call();
    if (token != null && token.isNotEmpty) {
      headers['Authorization'] = 'Bearer $token';
    }

    if (idempotencyKey != null && idempotencyKey.isNotEmpty) {
      headers['Idempotency-Key'] = idempotencyKey;
    }

    if (extra != null) headers.addAll(extra);

    return headers;
  }

  /// Decode a 2xx body. 204 or an empty body returns `null`.
  dynamic _decodeSuccess(http.Response response) {
    if (response.statusCode == 204) return null;

    final String text = response.body;
    if (text.trim().isEmpty) return null;

    final String contentType =
        response.headers['content-type']?.toLowerCase() ?? '';
    if (!contentType.contains('application/json')) {
      // Rare for FastAPI. Return the raw text; typed callers decide.
      return text;
    }

    try {
      return jsonDecode(text);
    } catch (_) {
      throw ApiError(
        status: response.statusCode,
        message: 'Failed to parse response JSON',
      );
    }
  }
}
